# Generated by Django 4.2.3 on 2023-07-25 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('UniqueNumber', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=3)),
                ('ResidentRegistration', models.CharField(max_length=13)),
                ('ResidentialArea', models.CharField(max_length=13)),
                ('MenberID', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=20)),
                ('BankAccount', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ReportList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarNum', models.CharField(max_length=8)),
                ('AfterUniqueNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_UniqueNumber', to='home.member')),
                ('BeforeUniqueNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before_UniqueNumber', to='home.member')),
            ],
        ),
        migrations.CreateModel(
            name='CarList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.DecimalField(decimal_places=10, max_digits=18)),
                ('Longitube', models.DecimalField(decimal_places=10, max_digits=18)),
                ('CarNum', models.CharField(max_length=8)),
                ('MenberID', models.CharField(max_length=6)),
                ('ReportStatus', models.CharField(choices=[('T', 'true'), ('F', 'false')], max_length=1)),
                ('UniqueNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carlist_UniqueNumber', to='home.member')),
            ],
        ),
    ]
