# Generated by Django 4.2.3 on 2023-07-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_carlist_table_alter_member_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportlist',
            name='AfterUniqueNumber',
        ),
        migrations.RemoveField(
            model_name='reportlist',
            name='BeforeUniqueNumber',
        ),
        migrations.DeleteModel(
            name='CarList',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='ReportList',
        ),
    ]
