# Generated by Django 4.2.3 on 2023-07-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_member_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='password',
            new_name='Password',
        ),
    ]
