# Generated by Django 4.2.3 on 2023-07-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='MenberID',
            field=models.CharField(max_length=10),
        ),
    ]
