# Generated by Django 4.2.3 on 2023-08-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_member_menberid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
