# Generated by Django 4.2.3 on 2023-08-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_menberid_member_memberid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlist',
            old_name='MenberID',
            new_name='MemberID',
        ),
    ]
