# Generated by Django 4.2.3 on 2023-08-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_menberid_carlist_memberid'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
