# Generated by Django 4.2.3 on 2023-08-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_carlist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportlist',
            name='AfterDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportlist',
            name='BeforeDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
