# Generated by Django 4.2.3 on 2023-08-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_reportlist_afterdate_reportlist_beforedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlist',
            name='UniqueNumber',
        ),
    ]
