# Generated by Django 4.2.3 on 2023-08-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_carlist_uniquenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='UniqueNumber',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='reportlist',
            name='AfterUniqueNumber',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='reportlist',
            name='BeforeUniqueNumber',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
