# Generated by Django 4.2.3 on 2023-08-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_carlist_uniquenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='Latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='carlist',
            name='Longitube',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
