# Generated by Django 4.2.3 on 2023-08-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_carlist_latitude_alter_carlist_longitube'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportlist',
            name='Afterimage',
            field=models.ImageField(blank=True, null=True, upload_to='blogimg'),
        ),
        migrations.AddField(
            model_name='reportlist',
            name='Beforeimage',
            field=models.ImageField(blank=True, null=True, upload_to='blogimg'),
        ),
    ]
