# Generated by Django 4.2.3 on 2023-08-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_reportlist_afterimage_reportlist_beforeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlist',
            name='Afterimage',
            field=models.ImageField(blank=True, null=True, upload_to='carimg'),
        ),
        migrations.AlterField(
            model_name='reportlist',
            name='Beforeimage',
            field=models.ImageField(blank=True, null=True, upload_to='carimg'),
        ),
    ]
